### ISSUE TITLE
Create end page and first page buttons with optional props

### ISSUE THREAD

**Issue by mohitkyadav** [mohitkyadav/react-pagination-nav#5]

**Comment by Tomekmularczyk** [comment]
I'll take this one too :)

**Comment by arpancodes** [comment]
Hey, I would like to take it up... :)
I believe with the optional props you are saying the title of the button? Please elaborate if I am not getting it :)
This is my first hacktoberfest would really love to contribute to react-pagination-nav

**Comment by rohan2734** [comment]
Hi i would like to work on this, can you elaborate the issue?

**Comment by mohitkyadav** [comment]
We have buttons for page numbers and next page and previous page. Similarly we want to have one button for last page and one button for first page.

**Comment by rohan2734** [comment]
oh ok understood, i would like to work on it. you can assign me on it, and i will put a PR soon.

**Comment by arpancodes** [comment]
Right, currently we just have the page toggle. First and last page buttons would be a good accessibility. I am also interested in doing it.
